-- 코드를 입력하세요
SELECT
    REST.REST_ID,
    REST.REST_NAME,
    REST.FOOD_TYPE,
    REST.FAVORITES,
    REST.ADDRESS,
    ROUND(AVG(RV.REVIEW_SCORE),2) AS 'SCORE'
FROM REST_INFO REST
INNER JOIN REST_REVIEW RV
ON REST.REST_ID = RV.REST_ID
GROUP BY REST_ID
HAVING ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, REST.FAVORITES DESC        
-- 서울, 식당ID, 식당이름, 음식종류, 즐겨찾기수, 주소, 리뷰 평균점수(round3), 평균DESC, 즐겨찾기수DESC