-- 코드를 입력하세요
SELECT
    AUTHOR.AUTHOR_ID AS '저자 ID',
    AUTHOR.AUTHOR_NAME AS '저자명',
    BOOK.CATEGORY AS '카테고리',
    SUM(BOOK.PRICE * BOOK_SALES.SALES) AS TOTAL_SALES
    # BOOK_SALES.SALES AS TOTAL_SALES 
FROM AUTHOR
JOIN BOOK ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
JOIN BOOK_SALES ON BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
WHERE BOOK_SALES.SALES_DATE BETWEEN DATE('2022-01-01') AND DATE('2022-01-31')
GROUP BY AUTHOR.AUTHOR_ID, BOOK.CATEGORY
ORDER BY AUTHOR.AUTHOR_ID, BOOK.CATEGORY DESC