-- 코드를 입력하세요
SELECT
    B.TITLE ,
    B.BOARD_ID ,
    R.REPLY_ID ,
    R.WRITER_ID ,
    R.CONTENTS ,
    DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS 'CREATED_DATE'
FROM USED_GOODS_BOARD B
INNER JOIN USED_GOODS_REPLY R
ON B.BOARD_ID = R.BOARD_ID
WHERE DATE(B.CREATED_DATE) BETWEEN DATE('2022-10-01') AND DATE('2022-10-31')
ORDER BY DATE(R.CREATED_DATE) ASC, B.TITLE ASC
-- 게시글제목 게시글ID 댓글ID 댓글작성자ID 댓글내용 댓글작성일